version: "3"

services:
  db-postgres-finance:
    image: postgres:alpine
    ports:
      - "5431:5432"
    container_name: "db-postgres-finance"
    restart: always
    volumes:
      - ./banco-de-dados-finance:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: franklin
      POSTGRES_PASSWORD: 1234

volumes:
  banco-de-dados-finance:
